imports:
  - { resource: ../services/common/**/*.yml }
  - { resource: ../services/front/**/*.yml }

services:
  _defaults:
    public: true

  kaudaj.module.blocks.block.query_handler.get_by_hook:
    public: true
    parent: kaudaj.module.blocks.block.query_handler.abstract
    class: Kaudaj\Module\Blocks\Domain\Block\QueryHandler\GetBlocksByHookHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\Blocks\Domain\Block\Query\GetBlocksByHook
