services:
  _defaults:
    public: true

  kaudaj.module.blocks.grid.data.factory.block:
    class: PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory
    arguments:
      - "@kaudaj.module.blocks.grid.query.block"
      - "@prestashop.core.hook.dispatcher"
      - "@prestashop.core.grid.query.doctrine_query_parser"
      - blocks

  kaudaj.module.blocks.grid.factory.block:
    class: PrestaShop\PrestaShop\Core\Grid\GridFactory
    arguments:
      - "@kaudaj.module.blocks.grid.definition.factory.block"
      - "@kaudaj.module.blocks.grid.data.factory.block"
      - "@prestashop.core.grid.filter.form_factory"
      - "@prestashop.core.hook.dispatcher"
