services:
  _defaults:
    public: true

  kaudaj.module.blocks.grid.query.block:
    public: true
    class: Kaudaj\Module\Blocks\Grid\Query\BlockQueryBuilder
    parent: prestashop.core.grid.abstract_query_builder
    arguments:
      - "@prestashop.core.query.doctrine_search_criteria_applicator"
      - '@=service("prestashop.adapter.legacy.context").getContext().language.id'
      - "@prestashop.adapter.shop.context"

  kaudaj.module.blocks.grid.query.block_group:
    public: true
    class: Kaudaj\Module\Blocks\Grid\Query\BlockGroupGridQueryBuilder
    parent: prestashop.core.grid.abstract_query_builder
    arguments:
      - "@prestashop.core.query.doctrine_search_criteria_applicator"
      - '@=service("prestashop.adapter.legacy.context").getContext().language.id'
      - '@=service("prestashop.adapter.legacy.context").getContext().shop.id'
