services:
  _defaults:
    public: true

  kaudaj.module.content_blocks.content_block.query_handler.abstract:
    abstract: true
    class: Kaudaj\Module\ContentBlocks\Domain\ContentBlock\QueryHandler\AbstractContentBlockQueryHandler
    arguments:
      - "@doctrine.orm.entity_manager"
