services:
  _defaults:
    public: true

  kaudaj.module.blocks.form.choice_provider.block_hook:
    public: true
    class: Kaudaj\Module\Blocks\Form\ChoiceProvider\BlockHookChoiceProvider
    arguments:
      - "@prestashop.core.command_bus"

  kaudaj.module.blocks.form.choice_provider.hook:
    class: Kaudaj\Module\Blocks\Form\ChoiceProvider\HookChoiceProvider
    arguments:
      $connection: "@doctrine.dbal.default_connection"
      $dbPrefix: "%database_prefix%"
