services:
  _defaults:
    public: true

  kaudaj.module.blocks.form.data_provider.block:
    class: Kaudaj\Module\Blocks\Form\DataProvider\BlockFormDataProvider
    arguments:
      - "@prestashop.core.command_bus"
      - '@prestashop.adapter.legacy.context'
