services:
  _defaults:
    public: true

  kaudaj.module.blocks.form.data_provider.block:
    class: Kaudaj\Module\Blocks\Form\DataProvider\BlockFormDataProvider
    arguments:
      - "@prestashop.core.command_bus"
      - "@kaudaj.module.blocks.form.data_provider.block_type"

  kaudaj.module.blocks.form.data_provider.block_type:
    class: Kaudaj\Module\Blocks\Form\DataProvider\BlockTypeFormDataProvider
    arguments:
      $legacyContext: "@prestashop.adapter.legacy.context"
      $blockTypeProvider: "@kaudaj.module.blocks.block_type_provider"

  kaudaj.module.blocks.form.data_provider.block_group:
    class: Kaudaj\Module\Blocks\Form\DataProvider\BlockGroupFormDataProvider
    arguments:
      - "@prestashop.core.command_bus"
