services:
  _defaults:
    public: true

  kaudaj.module.blocks.form.handler.block:
    class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler
    factory: "prestashop.core.form.identifiable_object.handler.form_handler_factory:create"
    arguments:
      - "@kaudaj.module.blocks.form.data_handler.block"

  kaudaj.module.blocks.form.handler.block_group:
    class: PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler
    factory: "prestashop.core.form.identifiable_object.handler.form_handler_factory:create"
    arguments:
      - "@kaudaj.module.blocks.form.data_handler.block_group"
