services:
  _defaults:
    public: true

  kaudaj.module.blocks.form.type.block:
    public: true
    parent: "form.type.translatable.aware"
    class: Kaudaj\Module\Blocks\Form\Type\BlockType
    arguments:
      - '@=service("kaudaj.module.blocks.form.choice_provider.block_group").getChoices()'
      - '@=service("kaudaj.module.blocks.form.choice_provider.hook").getChoices()'
    tags:
      - { name: form.type }

  kaudaj.module.blocks.form.type.block_type:
    public: true
    parent: "form.type.translatable.aware"
    class: Kaudaj\Module\Blocks\Form\Type\BlockTypeType
    arguments:
      - "@kaudaj.module.blocks.block_type_provider"
      - "@request_stack"
      - "@prestashop.core.command_bus"
      - "@kaudaj.module.blocks.form.type.multi_shop_checkbox_enabler"
    tags:
      - { name: form.type }

  kaudaj.module.blocks.form.type.multi_shop_checkbox_enabler:
    public: true
    class: Kaudaj\Module\Blocks\Form\Type\MultiShopCheckboxEnabler
    arguments:
      - "@prestashop.adapter.feature.multistore"
      - "@prestashop.adapter.shop.context"
      - "@doctrine.orm.entity_manager"
      - "@twig"

  kaudaj.module.blocks.form.type.block_picker:
    public: true
    parent: "form.type.translatable.aware"
    class: Kaudaj\Module\Blocks\Form\Type\BlockTypePicker
    tags:
      - { name: form.type }

  kaudaj.module.blocks.form.type.block_group:
    public: true
    parent: "form.type.translatable.aware"
    class: Kaudaj\Module\Blocks\Form\Type\BlockGroupType
    arguments:
      - '@=service("kaudaj.module.blocks.form.choice_provider.hook").getChoices()'
    tags:
      - { name: form.type }

  kaudaj.module.blocks.form.type.block.container:
    public: true
    parent: "form.type.translatable.aware"
    class: Kaudaj\Module\Blocks\Form\Type\Block\ContainerBlockType
    tags:
      - { name: form.type }

  kaudaj.module.blocks.form.type.block.text:
    public: true
    parent: "form.type.translatable.aware"
    class: Kaudaj\Module\Blocks\Form\Type\Block\TextBlockType
    tags:
      - { name: form.type }
