services:
  _defaults:
    public: true

  kaudaj.module.blocks.form.type.block:
    public: true
    parent: "form.type.translatable.aware"
    class: Kaudaj\Module\Blocks\Form\Type\BlockType
    arguments:
      - '@=service("kaudaj.module.blocks.form.choice_provider.hook").getChoices()'
      - '@prestashop.core.command_bus'
    tags:
      - { name: form.type }

  kaudaj.module.blocks.form.type.block.container:
    public: true
    parent: "form.type.translatable.aware"
    class: Kaudaj\Module\Blocks\Form\Type\Block\ContainerBlockType
    tags:
      - { name: form.type }

  kaudaj.module.blocks.form.type.block.text:
    public: true
    parent: "form.type.translatable.aware"
    class: Kaudaj\Module\Blocks\Form\Type\Block\TextBlockType
    tags:
      - { name: form.type }
