services:
  _defaults:
    public: true

  kaudaj.module.blocks.block_group.query_handler.abstract:
    abstract: true
    class: Kaudaj\Module\Blocks\Domain\BlockGroup\QueryHandler\AbstractBlockGroupQueryHandler
    arguments:
      - "@doctrine.orm.entity_manager"

  kaudaj.module.blocks.block_group.query_handler.get:
    public: true
    parent: kaudaj.module.blocks.block_group.query_handler.abstract
    class: Kaudaj\Module\Blocks\Domain\BlockGroup\QueryHandler\GetBlockGroupHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\Blocks\Domain\BlockGroup\Query\GetBlockGroup

  kaudaj.module.blocks.block_group.query_handler.get_by_name:
    public: true
    parent: kaudaj.module.blocks.block_group.query_handler.abstract
    class: Kaudaj\Module\Blocks\Domain\BlockGroup\QueryHandler\GetBlockGroupByNameHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\Blocks\Domain\BlockGroup\Query\GetBlockGroupByName

  kaudaj.module.blocks.block_group.query_handler.get_all:
    public: true
    parent: kaudaj.module.blocks.block_group.query_handler.abstract
    class: Kaudaj\Module\Blocks\Domain\BlockGroup\QueryHandler\GetBlockGroupsHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\Blocks\Domain\BlockGroup\Query\GetBlockGroups

  kaudaj.module.blocks.block_group.query_handler.get_block_for_editing:
    public: true
    parent: kaudaj.module.blocks.block_group.query_handler.abstract
    class: Kaudaj\Module\Blocks\Domain\BlockGroup\QueryHandler\GetBlockGroupForEditingHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\Blocks\Domain\BlockGroup\Query\GetBlockGroupForEditing

  kaudaj.module.blocks.block_group.command_handler.abstract:
    abstract: true
    class: Kaudaj\Module\Blocks\Domain\BlockGroup\CommandHandler\AbstractBlockGroupCommandHandler
    arguments:
      - "@doctrine.orm.entity_manager"

  kaudaj.module.blocks.block_group.command_handler.add:
    public: true
    parent: kaudaj.module.blocks.block_group.command_handler.abstract
    class: Kaudaj\Module\Blocks\Domain\BlockGroup\CommandHandler\AddBlockGroupHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\Blocks\Domain\BlockGroup\Command\AddBlockGroupCommand

  kaudaj.module.blocks.block_group.command_handler.edit:
    public: true
    parent: kaudaj.module.blocks.block_group.command_handler.abstract
    class: Kaudaj\Module\Blocks\Domain\BlockGroup\CommandHandler\EditBlockGroupHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\Blocks\Domain\BlockGroup\Command\EditBlockGroupCommand

  kaudaj.module.blocks.block_group.command_handler.delete:
    public: true
    parent: kaudaj.module.blocks.block_group.command_handler.abstract
    class: Kaudaj\Module\Blocks\Domain\BlockGroup\CommandHandler\DeleteBlockGroupHandler
    tags:
      - name: tactician.handler
        command: Kaudaj\Module\Blocks\Domain\BlockGroup\Command\DeleteBlockGroupCommand
