services:
  _defaults:
    public: true

  kaudaj.module.blocks.block.query_handler.abstract:
    abstract: true
    class: Kaudaj\Module\Blocks\Domain\Block\QueryHandler\AbstractBlockQueryHandler
    arguments:
      - "@doctrine.orm.entity_manager"

  kaudaj.module.blocks.block_type_provider.factory:
    class: Kaudaj\Module\Blocks\BlockTypeProviderFactory

  kaudaj.module.blocks.block_type_provider:
    class: Kaudaj\Module\Blocks\BlockTypeProvider
    factory: ["@kaudaj.module.blocks.block_type_provider.factory", "create"]
    arguments:
      - 'actionGetBlockTypes'

  kaudaj.module.blocks.block_renderer:
    class: Kaudaj\Module\Blocks\BlockRenderer
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext().language.id'
      - '@kaudaj.module.blocks.block_type_provider'
