services:
  _defaults:
    public: true

  kaudaj.module.blocks.block.query_handler.abstract:
    abstract: true
    class: Kaudaj\Module\Blocks\Domain\Block\QueryHandler\AbstractBlockQueryHandler
    arguments:
      - "@doctrine.orm.entity_manager"

  kaudaj.module.blocks.block_type_provider:
    class: Kaudaj\Module\Blocks\BlockTypeProvider
    arguments:
      - "@prestashop.adapter.legacy.context"
