services:
  _defaults:
    public: true

  kaudaj.module.blocks.abstract_block_type_provider:
    abstract: true
    class: Kaudaj\Module\Blocks\BlockTypeProvider
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext().language.id'

  kaudaj.module.blocks.block_type_provider:
    public: true
    parent: kaudaj.module.blocks.abstract_block_type_provider
    class: Kaudaj\Module\Blocks\BlockTypeProvider
    arguments:
      - "actionGetBlockTypes"
      - "@kaudaj.module.blocks.block_context"

  kaudaj.module.blocks.renderer.block_group:
    class: Kaudaj\Module\Blocks\Renderer\BlockGroupRenderer
    arguments:
      - "@kaudaj.module.blocks.block_type_provider"
      - "@kaudaj.module.blocks.block_context"

  kaudaj.module.blocks.block_context:
    class: Kaudaj\Module\Blocks\BlockContext
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext().language.id'
      - "@prestashop.adapter.shop.context"
