kj_blocks:
  path: /
  methods: [GET]
  defaults:
    _controller: 'Kaudaj\Module\Blocks\Controller\Admin\BlockController::indexAction'
    _legacy_controller: KJBlocks

kj_blocks_blocks:
  resource: "block.yml"
  prefix: /blocks

kj_blocks_settings:
  resource: "settings.yml"
  prefix: /settings
