kj_blocks_settings_index:
  path: /
  methods: [GET]
  defaults:
    _controller: 'Kaudaj\Module\Blocks\Controller\Admin\SettingsController::indexAction'
    _legacy_controller: KJBlocksSettings

kj_blocks_settings_general_save:
  path: /general
  methods: [POST, PATCH]
  defaults:
    _controller: 'Kaudaj\Module\Blocks\Controller\Admin\SettingsController::processGeneralFormAction'
    _legacy_controller: KJBlocksSettings
    _legacy_link: KJBlocksSettings:update
