services:
  _defaults:
    public: true

  kaudaj.module.content_blocks.form.choice_provider.content_block_hook:
    public: true
    class: Kaudaj\Module\ContentBlocks\Form\ChoiceProvider\ContentBlockHookChoiceProvider
    arguments:
      - "@prestashop.core.command_bus"

  kaudaj.module.content_blocks.form.choice_provider.hook:
    class: Kaudaj\Module\ContentBlocks\Form\ChoiceProvider\HookChoiceProvider
    arguments:
      $connection: "@doctrine.dbal.default_connection"
      $dbPrefix: "%database_prefix%"
