services:
  _defaults:
    public: true

  kaudaj.module.blocks.form.data_handler.block:
    class: Kaudaj\Module\Blocks\Form\DataHandler\BlockFormDataHandler
    arguments:
      - '@prestashop.core.command_bus'