services:
  _defaults:
    public: true

  kaudaj.module.content_blocks.form.data_handler.content_block:
    class: Kaudaj\Module\ContentBlocks\Form\DataHandler\ContentBlockFormDataHandler
    arguments:
      - '@prestashop.core.command_bus'