services:
  _defaults:
    public: true

  kaudaj.module.content_blocks.form.data_provider.content_block:
    class: Kaudaj\Module\ContentBlocks\Form\DataProvider\ContentBlockFormDataProvider
    arguments:
      - "@prestashop.core.command_bus"
