services:
  _defaults:
    public: true

  kaudaj.module.content_blocks.form.type.content_block:
    public: true
    parent: "form.type.translatable.aware"
    class: Kaudaj\Module\ContentBlocks\Form\Type\ContentBlockType
    arguments:
      - '@=service("kaudaj.module.content_blocks.form.choice_provider.hook").getChoices()'
    tags:
      - { name: form.type }
