services:
  _defaults:
    public: true

  kaudaj.module.blocks.form.type.block:
    public: true
    parent: "form.type.translatable.aware"
    class: Kaudaj\Module\Blocks\Form\Type\BlockType
    arguments:
      - '@=service("kaudaj.module.blocks.form.choice_provider.hook").getChoices()'
    tags:
      - { name: form.type }
