imports:
  - { resource: services/**/*.yml }

services:
  _defaults:
    public: true

  kaudaj.module.blocks.form.settings.general_configuration:
    class: Kaudaj\Module\Blocks\Form\Settings\GeneralConfiguration
    arguments:
      - "@prestashop.adapter.legacy.configuration"
      - "@prestashop.adapter.shop.context"
      - "@prestashop.adapter.multistore_feature"

  kaudaj.module.blocks.form.settings.general_type:
    class: 'Kaudaj\Module\Blocks\Form\Settings\GeneralType'
    parent: "form.type.translatable.aware"
    public: true
    tags:
      - { name: form.type }

  kaudaj.module.blocks.form.settings.general_form_data_provider:
    class: 'Kaudaj\Module\Blocks\Form\Settings\GeneralFormDataProvider'
    arguments:
      - "@kaudaj.module.blocks.form.settings.general_configuration"

  kaudaj.module.blocks.form.settings.general_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - "@form.factory"
      - "@prestashop.core.hook.dispatcher"
      - "@kaudaj.module.blocks.form.settings.general_form_data_provider"
      - 'Kaudaj\Module\Blocks\Form\Settings\GeneralType'
      - "General"

  kaudaj.module.blocks.event_listener.block_hooks_updater:
    class: 'Kaudaj\Module\Blocks\EventListener\BlockHooksUpdater'
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@=service("prestashop.adapter.shop.context").getContextShopID()'
    tags:
      -
        name: 'doctrine.orm.entity_listener'
        event: 'postUpdate'
        entity: 'Kaudaj\Module\Blocks\Entity\Block'
      -
        name: 'doctrine.orm.entity_listener'
        event: 'postPersist'
        entity: 'Kaudaj\Module\Blocks\Entity\Block'
      -
        name: 'doctrine.orm.entity_listener'
        event: 'postRemove'
        entity: 'Kaudaj\Module\Blocks\Entity\Block'
