imports:
  - { resource: services/admin/**/*.yml }
  - { resource: services/common/**/*.yml }

services:
  _defaults:
    public: true

  kaudaj.module.blocks.event_listener.block_hooks_updater:
    class: 'Kaudaj\Module\Blocks\EventListener\BlockHooksUpdater'
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@=service("prestashop.adapter.shop.context").getContextShopID()'
    tags:
      -
        name: 'doctrine.orm.entity_listener'
        event: 'postUpdate'
        entity: 'Kaudaj\Module\Blocks\Entity\Block'
      -
        name: 'doctrine.orm.entity_listener'
        event: 'postPersist'
        entity: 'Kaudaj\Module\Blocks\Entity\Block'
      -
        name: 'doctrine.orm.entity_listener'
        event: 'postRemove'
        entity: 'Kaudaj\Module\Blocks\Entity\Block'

