services:
  _defaults:
    public: true

  kaudaj.module.content_blocks.grid.definition.factory.content_block:
    public: true
    class: Kaudaj\Module\ContentBlocks\Grid\Definition\Factory\ContentBlockGridDefinitionFactory
    parent: prestashop.core.grid.definition.factory.abstract_grid_definition
    arguments:
      - "@kaudaj.module.content_blocks.form.choice_provider.content_block_hook"
      - "@prestashop.core.admin.admin_filter.repository"
      - "@prestashop.adapter.data_provider.employee"
      - "@prestashop.adapter.shop.context"

  kaudaj.module.content_blocks.grid.position.content_block_grid_position_updater:
    class: 'Kaudaj\Module\ContentBlocks\Grid\Position\ContentBlockGridPositionUpdater'
    arguments:
      - '@kaudaj.module.content_blocks.grid.position.update_handler.content_block_position_update_handler'

  kaudaj.module.content_blocks.grid.position.update_handler.content_block_position_update_handler:
    class: 'Kaudaj\Module\ContentBlocks\Grid\Position\UpdateHandler\ContentBlockPositionUpdateHandler'
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'

  kaudaj.module.content_blocks.grid.position_definition.content_block:
    class: 'PrestaShop\PrestaShop\Core\Grid\Position\PositionDefinition'
    arguments:
      $table: !php/const Kaudaj\Module\ContentBlocks\Repository\ContentBlockHookRepository::TABLE_NAME
      $idField: "id_content_block"
      $positionField: "position"
      $parentIdField: "id_hook"
