services:
  _defaults:
    public: true

  kaudaj.module.content_blocks.grid.data.factory.content_block:
    class: PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory
    arguments:
      - "@kaudaj.module.content_blocks.grid.query.content_block"
      - "@prestashop.core.hook.dispatcher"
      - "@prestashop.core.grid.query.doctrine_query_parser"
      - content_blocks

  kaudaj.module.content_blocks.grid.factory.content_block:
    class: PrestaShop\PrestaShop\Core\Grid\GridFactory
    arguments:
      - "@kaudaj.module.content_blocks.grid.definition.factory.content_block"
      - "@kaudaj.module.content_blocks.grid.data.factory.content_block"
      - "@prestashop.core.grid.filter.form_factory"
      - "@prestashop.core.hook.dispatcher"
