name: Build
on: [push, pull_request]

jobs:
  deploy:
    name: build dependencies & create artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      # Optional step compiling JS files
      - name: Build JS dependencies
        uses: PrestaShopCorp/github-action-build-js/12@v1.0
        with:
          cmd: yarn
          path: ./_dev

      # Install PHP dependencies (Production ONLY)
      - name: Install composer dependencies
        run: composer install --no-dev -o

      # Remove development files
      - name: Clean-up project
        uses: PrestaShopCorp/github-action-clean-before-deploy@v1.0

      - name: Prepare auto-index tool
        run: composer global require prestashop/autoindex

      - name: Generate index.php
        run: ~/.composer/vendor/bin/autoindex

      - name: Create and upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ github.event.repository.name }}
          path: ../
